version: '3'
services:
    server:
        image: "anton95/multi-server"
        mem_limit: 128m
        hostname: api
        environment:
            - REDIS_HOST=$REDIS_HOST
            - REDIS_PORT=$REDIS_PORT
            - PGUSER=$PGUSER
            - PGHOST=$PGHOST
            - PGDATABASE=$PGDATABASE
            - PGPASSWORD=$PGPASSWORD
            - PGPORT=$PGPORT
            
    client:
        image: "anton95/multi-client"
        mem_limit: 128m
        hostname: client
    
    worker:
        image: "anton95/multi-worker"
        mem_limit: 128m
        hostname: worker
        environment:
            - REDIS_HOST=$REDIS_HOST
            - REDIS_PORT=$REDIS_PORT
    
    nginx:
        image: "anton95/multi-nginx"
        mem_limit: 128m
        hostname: nginx
        ports:
            - '80:80'